version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/planeja-ai
      dockerfile: Dockerfile
    container_name: planeja-ai-frontend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: planeja-ai-backend
    restart: unless-stopped
    ports:
      - "3001:3001"

  nginx:
    image: nginx:1.25-alpine
    container_name: planeja-ai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/certificates/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./infra/certificates/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - frontend
      - backend
